# Site settings
# These are used to personalize your new site.
title: A'Myah Temple # your name here
logo: "/images/IMG_8681.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2027)
  <br /><br />
  </pdf/Resume.pdf>View My Resume
  <br /><br />
  <a href="https://www.linkedin.com/in/amyahtemple0089/jobs/">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  myahthub # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

